version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless@3

  pre_build:
    commands:
      - serverless --version

  build:
    commands:
      - serverless deploy --stage prod
