version: 0.3

phases:
  install:
    runtime-versions:
      nodejs: 20.19.6
    commands:
      - npm install -g serverless
      - npm install

  build:
    commands:
      - serverless deploy --stage prod

artifacts:
  files:
    - '**/*'
